name: CI - Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
      continue-on-error: true
      
    - name: Check HTML syntax
      run: |
        echo "Checking HTML files..."
        find . -name "*.html" -exec echo "Checking {}" \;
        
    - name: Check CSS syntax
      run: |
        echo "Checking CSS files..."
        find . -name "*.css" -exec echo "Checking {}" \;
        
    - name: Check JavaScript syntax
      run: |
        echo "Checking JavaScript files..."
        find . -name "*.js" -exec node -c {} \;
        
    - name: Validate file structure
      run: |
        echo "Validating project structure..."
        echo "Required files check:"
        [ -f "index.html" ] && echo "✅ index.html exists" || echo "❌ index.html missing"
        [ -f "styles.css" ] && echo "✅ styles.css exists" || echo "❌ styles.css missing"
        [ -f "app.js" ] && echo "✅ app.js exists" || echo "❌ app.js missing"
        [ -d "template" ] && echo "✅ template directory exists" || echo "❌ template directory missing"
        
    - name: Check for broken links in HTML
      run: |
        echo "Checking for basic HTML structure..."
        if [ -f index.html ]; then
          grep -q "<!DOCTYPE html>" index.html && echo "✅ DOCTYPE found" || echo "⚠️  DOCTYPE missing"
          grep -q "<html" index.html && echo "✅ HTML tag found" || echo "❌ HTML tag missing"
          grep -q "</html>" index.html && echo "✅ HTML closing tag found" || echo "❌ HTML closing tag missing"
        fi
